<?php /* Smarty version 2.6.20, created on 2017-09-16 19:52:29
         compiled from header.tpl */

$this->_cache_serials['/home/osba/public_html/Smarty/templates_c/%%F7^F7F^F7F34188%%header.tpl.inc'] = '5b495df0b2fb938c4ef7e34559d541cc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'default', 'header.tpl', 75, false),array('modifier', 'escape', 'header.tpl', 92, false),array('function', 'dropdown_menu_video_categories', 'header.tpl', 367, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 375, false),)), $this); ?>
<?php
function _smarty_tplfunc_5b495df0b2fb938c4ef7e34559d541cc_0(&$_smarty)
{
echo smarty_art_html_list_categories(array('max_levels' => 3), $_smarty);
}



?>
